### ISSUE TITLE
[suggestion&bug] command

### ISSUE THREAD

**Issue by shockpast** [XenPare/XPA#1]
help command for srcds console, it useful because not everyone knows every command in xpa.
![изображение](https://user-images.githubusercontent.com/81193284/177817406-8cbbc66c-8549-4632-bf8e-c58029a19d06.png)

by the way, error in srcds when trying to type in: xpa menu (i know that people shouldn't type that, but that error is annoying)
![изображение](https://user-images.githubusercontent.com/81193284/177817692-0c32e8ba-05e0-44c9-8019-cabd021c995d.png)

**Comment by cresterienvogel** [comment]
Hi!

xpa help command has just been added.
Commands such as xpa teamlist and others have been optimized for console use.

Thanks for letting us know about the error!
Commands such as xpa menu can no longer be invoked from the console.
